export const AD_LIST_REQUEST = 'AD_LIST_REQUEST'
export const AD_LIST_SUCCESS = 'AD_LIST_SUCCESS'
export const AD_LIST_FAIL = 'AD_LIST_FAIL'

export const AD_DETAILS_REQUEST = 'AD_DETAILS_REQUEST'
export const AD_DETAILS_SUCCESS = 'AD_DETAILS_SUCCESS'
export const AD_DETAILS_FAIL = 'AD_DETAILS_FAIL'

export const AD_DELETE_REQUEST = 'AD_DELETE_REQUEST'
export const AD_DELETE_SUCCESS = 'AD_DELETE_SUCCESS'
export const AD_DELETE_FAIL = 'AD_DELETE_FAIL'

export const AD_CREATE_REQUEST = 'AD_CREATE_REQUEST'
export const AD_CREATE_SUCCESS = 'AD_CREATE_SUCCESS'
export const AD_CREATE_FAIL = 'AD_CREATE_FAIL'
export const AD_CREATE_RESET = 'AD_CREATE_RESET'

export const AD_UPDATE_REQUEST = 'AD_UPDATE_REQUEST'
export const AD_UPDATE_SUCCESS = 'AD_UPDATE_SUCCESS'
export const AD_UPDATE_FAIL = 'AD_UPDATE_FAIL'
export const AD_UPDATE_RESET = 'AD_UPDATE_RESET'


export const AD_TOP_REQUEST = 'AD_TOP_REQUEST'
export const AD_TOP_SUCCESS = 'AD_TOP_SUCCESS'
export const AD_TOP_FAIL = 'AD_TOP_FAIL'
